FROM node:18-alpine AS build
WORKDIR /app
COPY frontend-angular/package*.json ./
RUN npm ci
COPY frontend-angular/ ./
RUN npm run build -- --configuration=production

FROM nginx:alpine
COPY --from=build /app/dist/frontend-angular/browser /usr/share/nginx/html
COPY frontend-angular/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]